### ISSUE TITLE
OpenFace tool not found

### ISSUE THREAD

**Issue by Hugh0110** [thuiar/MMSA-FET#16]
您好，当我运行以下代码语句时：
from MSA_FET import FeatureExtractionTool
fet = FeatureExtractionTool("openface")
feature = fet.run_single('E:/CH-SIMS数据集/MSA Datasets/SIMS/Raw/video_0001/0001.mp4', out_file='E:/MME/feature_V.pkl',
                return_type='pt')
出现了如下错误：

MMSA-FET - ========================== MMSA-FET Started ==========================
MMSA-FET - Temporary directory: C:\Users\Hugh\.MMSA-FET/tmp
MMSA-FET - Log file: 'C:\Users\Hugh\.MMSA-FET/log\MMSA-FET.log'
MMSA-FET - Config: {'video': {'tool': 'openface', 'fps': 25, 'multiFace': {'enable': False, 'device': 'cuda:0', 'facedetScale': 0.25, 'minTrack': 10, 'numFailedDet': 10, 'minFaceSize': 1, 'cropScale': 0.4}, 'average_over': 1, 'args': {'hogalign': False, 'simalign': False, 'nobadaligned': False, 'landmark_2D': True, 'landmark_3D': False, 'pdmparams': False, 'head_pose': True, 'action_units': True, 'gaze': False, 'tracked': False}}}
MMSA-FET - Initializing OpenFace video feature extractor...
MMSA-FET - Failed to initialize mediapipeExtractor.
MMSA-FET - An Error Occured:
Traceback (most recent call last):
  File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 299, in run_single
    self.__init_extractors()
  File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 129, in __init_extractors
    self.video_extractor = VIDEO_EXTRACTOR_MAP[extractor_name](video_cfg, self.logger)
  File "E:\miniconda3\lib\site-packages\MSA_FET\extractors\video\openface.py", line 38, in __init__
    raise e
  File "E:\miniconda3\lib\site-packages\MSA_FET\extractors\video\openface.py", line 35, in __init__
    raise FileNotFoundError("OpenFace tool not found.")
FileNotFoundError: OpenFace tool not found.
Traceback (most recent call last):
  File "E:\MME\test.py", line 17, in <module>
    feature = fet.run_single('E:/CH-SIMS数据集/MSA Datasets/SIMS/Raw/video_0001/0001.mp4', out_file='E:/MME/feature_V.pkl',
  File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 335, in run_single
    raise e
  File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 299, in run_single
    self.__init_extractors()
  File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 129, in __init_extractors
    self.video_extractor = VIDEO_EXTRACTOR_MAP[extractor_name](video_cfg, self.logger)
  File "E:\miniconda3\lib\site-packages\MSA_FET\extractors\video\openface.py", line 38, in __init__
    raise e
  File "E:\miniconda3\lib\site-packages\MSA_FET\extractors\video\openface.py", line 35, in __init__
    raise FileNotFoundError("OpenFace tool not found.")
FileNotFoundError: OpenFace tool not found.

我使用的是Windows 10系统和Python 3.9，能够正常提取音频特征，请问可能是什么原因导致视频特征提取报错呢？

**Comment by Hugh0110** [comment]
> 请问您是否按照说明运行了 `python -m MSA_FET install` 命令？
是的，因为无法连接到Google Drive，所以我按照您的说明下载了ext文件，解压缩后将其放置在了E:\miniconda3\Lib\site-packages\MSA_FET文件夹路径下。

**Comment by Hugh0110** [comment]
> 请问您是否按照说明运行了 `python -m MSA_FET install` 命令？

是的，因为无法连接到Google Drive，所以我下载了exts压缩文件将其解压后放到了E:\miniconda3\Lib\site-packages\MSA_FET路径下。

**Comment by Hugh0110** [comment]
另外在运行如下代码时：
fet = FeatureExtractionTool("mediapipe")
feature = fet.run_single(in_file='E:/CH-SIMS数据集/MSA Datasets/SIMS/Raw/video_0001/0001.mp4',
                out_file='E:/MME/feature_V.pkl', return_type='pt')
出现了以下问题：
TypeError: extract() got an unexpected keyword argument 'tool_output'

我将main文件中的160行代码：
video_result = self.video_extractor.extract(self.tmp_dir, name, tool_output=self.verbose>0)
改为：
video_result = self.video_extractor.extract(self.tmp_dir, name)
之后可以正常提取特征。

**Comment by shiyanshi2233** [comment]
您好，请问您的问题解决了吗？我在使用openface时遇到了相同的问题，使用的是Windows 10系统和python3.8。同样无法连接到Google Drive，下载压缩文件后放到了\anaconda\envs\pytorch3.8\Lib\site-packages\MSA_FET\exts路径下

**Comment by shiyanshi2233** [comment]
> 您好，当我运行以下代码语句时： from MSA_FET import FeatureExtractionTool fet = FeatureExtractionTool("openface") feature = fet.run_single('E:/CH-SIMS数据集/MSA Datasets/SIMS/Raw/video_0001/0001.mp4', out_file='E:/MME/feature_V.pkl', return_type='pt') 出现了如下错误：
> 
> MMSA-FET - ========================== MMSA-FET Started ========================== MMSA-FET - Temporary directory: C:\Users\Hugh.MMSA-FET/tmp MMSA-FET - Log file: 'C:\Users\Hugh.MMSA-FET/log\MMSA-FET.log' MMSA-FET - Config: {'video': {'tool': 'openface', 'fps': 25, 'multiFace': {'enable': False, 'device': 'cuda:0', 'facedetScale': 0.25, 'minTrack': 10, 'numFailedDet': 10, 'minFaceSize': 1, 'cropScale': 0.4}, 'average_over': 1, 'args': {'hogalign': False, 'simalign': False, 'nobadaligned': False, 'landmark_2D': True, 'landmark_3D': False, 'pdmparams': False, 'head_pose': True, 'action_units': True, 'gaze': False, 'tracked': False}}} MMSA-FET - Initializing OpenFace video feature extractor... MMSA-FET - Failed to initialize mediapipeExtractor. MMSA-FET - An Error Occured: Traceback (most recent call last): File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 299, in run_single self.__init_extractors() File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 129, in __init_extractors self.video_extractor = VIDEO_EXTRACTOR_MAP[extractor_name](video_cfg, self.logger) File "E:\miniconda3\lib\site-packages\MSA_FET\extractors\video\openface.py", line 38, in **init** raise e File "E:\miniconda3\lib\site-packages\MSA_FET\extractors\video\openface.py", line 35, in **init** raise FileNotFoundError("OpenFace tool not found.") FileNotFoundError: OpenFace tool not found. Traceback (most recent call last): File "E:\MME\test.py", line 17, in feature = fet.run_single('E:/CH-SIMS数据集/MSA Datasets/SIMS/Raw/video_0001/0001.mp4', out_file='E:/MME/feature_V.pkl', File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 335, in run_single raise e File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 299, in run_single self.__init_extractors() File "E:\miniconda3\lib\site-packages\MSA_FET\main.py", line 129, in __init_extractors self.video_extractor = VIDEO_EXTRACTOR_MAP[extractor_name](video_cfg, self.logger) File "E:\miniconda3\lib\site-packages\MSA_FET\extractors\video\openface.py", line 38, in **init** raise e File "E:\miniconda3\lib\site-packages\MSA_FET\extractors\video\openface.py", line 35, in **init** raise FileNotFoundError("OpenFace tool not found.") FileNotFoundError: OpenFace tool not found.
> 
> 我使用的是Windows 10系统和Python 3.9，能够正常提取音频特征，请问可能是什么原因导致视频特征提取报错呢？

**Comment by Hugh0110** [comment]
> 您好，请问您的问题解决了吗？我在使用openface时遇到了相同的问题，使用的是Windows 10系统和python3.8。同样无法连接到Google Drive，下载压缩文件后放到了\anaconda\envs\pytorch3.8\Lib\site-packages\MSA_FET\exts路径下

暂时还没有解决，依旧无法提取特征

**Comment by shiyanshi2233** [comment]
> > 您好，请问您的问题解决了吗？我在使用openface时遇到了相同的问题，使用的是Windows 10系统和python3.8。同样无法连接到Google Drive，下载压缩文件后放到了\anaconda\envs\pytorch3.8\Lib\site-packages\MSA_FET\exts路径下
> 
> 暂时还没有解决，依旧无法提取特征

您好，我根据另一条提问：提取视频特征打印不成功 中的方法,官网下载openface，替换了百度云下载的exts中openface文件夹中的文件，解决了openface tool not found 的问题

**Comment by Hugh0110** [comment]
> > > 您好，请问您的问题解决了吗？我在使用openface时遇到了相同的问题，使用的是Windows 10系统和python3.8。同样无法连接到Google Drive，下载压缩文件后放到了\anaconda\envs\pytorch3.8\Lib\site-packages\MSA_FET\exts路径下
> > 
> > 
> > 暂时还没有解决，依旧无法提取特征
> 
> 您好，我根据另一条提问：提取视频特征打印不成功 中的方法,官网下载openface，替换了百度云下载的exts中openface文件夹中的文件，解决了openface tool not found 的问题

谢谢您的帮助，我替换之后显示还是需要下载CEN配置文件才能够运行，我正在下载。

**Comment by ttrikn** [comment]
> 

您好，我也遇到了相同的问题，请问您解决这个问题了吗？我在官网中下载openface替换掉原先exts中的openface文件夹之后，出现了另一条issue“提取视频特征打印不成功“里的问题：FileNotFoundError: [WinError 2] 系统找不到指定的文件。
因为CEN文件是视线估计中用来检测闭眼状态的模型，所以我不确定下载这个文件是否会对这个问题的解决起到帮助。请问您在下载CEN文件后可以正常运行了吗？

**Comment by ttrikn** [comment]
> > > > 您好，请问您的问题解决了吗？我在使用openface时遇到了相同的问题，使用的是Windows 10系统和python3.8。同样无法连接到Google Drive，下载压缩文件后放到了\anaconda\envs\pytorch3.8\Lib\site-packages\MSA_FET\exts路径下
> > > 
> > > 
> > > 暂时还没有解决，依旧无法提取特征
> > 
> > 
> > 您好，我根据另一条提问：提取视频特征打印不成功 中的方法,官网下载openface，替换了百度云下载的exts中openface文件夹中的文件，解决了openface tool not found 的问题
> 
> 谢谢您的帮助，我替换之后显示还是需要下载CEN配置文件才能够运行，我正在下载。

**Comment by ttrikn** [comment]
> > > > 您好，请问您的问题解决了吗？我在使用openface时遇到了相同的问题，使用的是Windows 10系统和python3.8。同样无法连接到Google Drive，下载压缩文件后放到了\anaconda\envs\pytorch3.8\Lib\site-packages\MSA_FET\exts路径下
> > > 
> > > 
> > > 暂时还没有解决，依旧无法提取特征
> > 
> > 
> > 您好，我根据另一条提问：提取视频特征打印不成功 中的方法,官网下载openface，替换了百度云下载的exts中openface文件夹中的文件，解决了openface tool not found 的问题
> 
> 谢谢您的帮助，我替换之后显示还是需要下载CEN配置文件才能够运行，我正在下载。

您好，我也遇到了相同的问题，请问您解决这个问题了吗？我在官网中下载openface替换掉原先exts中的openface文件夹之后，出现了另一条issue“提取视频特征打印不成功“里的问题：FileNotFoundError: [WinError 2] 系统找不到指定的文件。
因为CEN文件是视线估计中用来检测闭眼状态的模型，所以我不确定下载这个文件是否会对这个问题的解决起到帮助。请问您在下载CEN文件后可以正常运行了吗？

**Comment by ttrikn** [comment]
> > > > > 您好，请问您的问题解决了吗？我在使用openface时遇到了相同的问题，使用的是Windows 10系统和python3.8。同样无法连接到Google Drive，下载压缩文件后放到了\anaconda\envs\pytorch3.8\Lib\site-packages\MSA_FET\exts路径下
> > > > 
> > > > 
> > > > 暂时还没有解决，依旧无法提取特征
> > > 
> > > 
> > > 您好，我根据另一条提问：提取视频特征打印不成功 中的方法,官网下载openface，替换了百度云下载的exts中openface文件夹中的文件，解决了openface tool not found 的问题
> > 
> > 
> > 谢谢您的帮助，我替换之后显示还是需要下载CEN配置文件才能够运行，我正在下载。
> 
> 您好，我也遇到了相同的问题，请问您解决这个问题了吗？我在官网中下载openface替换掉原先exts中的openface文件夹之后，出现了另一条issue“提取视频特征打印不成功“里的问题：FileNotFoundError: [WinError 2] 系统找不到指定的文件。 因为CEN文件是视线估计中用来检测闭眼状态的模型，所以我不确定下载这个文件是否会对这个问题的解决起到帮助。请问您在下载CEN文件后可以正常运行了吗？

已解决，CEN文件确实是必需的。另外，”FileNotFoundError: [WinError 2] 系统找不到指定的文件“这个错误也有可能是ffmpeg这个软件包导致的。除了”ffmpeg-python“（我的是0.2.0版本）这个软件包之外，还需要从ffmpeg官网或者在conda中下载安装“ffmpeg”（我的是2.7.0版本），并将其正确配置到系统路径或虚拟环境中。

**Comment by moom2572** [comment]
请问下载的cen文件放到了哪个位置啊

**Comment by 05Pikachu24** [comment]
> > > 您好，请问您的问题解决了吗？我在使用openface时遇到了相同的问题，使用的是Windows 10系统和python3.8。同样无法连接到Google Drive，下载压缩文件后放到了\anaconda\envs\pytorch3.8\Lib\site-packages\MSA_FET\exts路径下
> > 
> > 
> > 暂时还没有解决，依旧无法提取特征
> 
> 您好，我根据另一条提问：提取视频特征打印不成功 中的方法,官网下载openface，替换了百度云下载的exts中openface文件夹中的文件，解决了openface tool not found 的问题

您好，原先exts下的openface内的三个文件需要删除 再把官网下载的openface放进去嘛？还是不用管。我两种情况都试了，还是报not found这个错误
